-- MemeRadar V2 database structure.
-- Run this only in a new Supabase project. Existing projects should use migrations.

create table if not exists public.tokens (
  mint_address text primary key,
  symbol text not null,
  name text not null,
  image_url text,
  dex_url text,
  pair_address text,
  source text not null default 'dexscreener',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.token_snapshots (
  id bigint generated by default as identity primary key,
  mint_address text not null references public.tokens(mint_address) on delete cascade,
  captured_at timestamptz not null,
  price_usd numeric,
  market_cap_usd numeric,
  liquidity_usd numeric,
  volume_5m_usd numeric,
  volume_1h_usd numeric,
  buys_5m integer,
  sells_5m integer,
  buy_pressure numeric,
  pair_age_minutes integer,
  memeradar_score integer,
  momentum_score integer,
  liquidity_score integer,
  participation_score integer,
  safety_score integer,
  source text not null default 'dexscreener',
  unique (mint_address, captured_at)
);

create table if not exists public.token_risk_checks (
  mint_address text primary key references public.tokens(mint_address) on delete cascade,
  checked_at timestamptz not null default now(),
  mint_authority text,
  mint_authority_revoked boolean not null default false,
  freeze_authority text,
  freeze_authority_revoked boolean not null default false,
  metadata_mutable boolean,
  top_10_holder_pct numeric,
  risk_score integer not null default 0,
  status text not null default 'pending',
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists public.alert_rules (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  name text not null,
  enabled boolean not null default true,
  conditions jsonb not null default '{}'::jsonb,
  delivery_channels jsonb not null default '["in_app"]'::jsonb,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  owner_scope text not null default 'private-site-owner',
  match_count integer not null default 0
);

create table if not exists public.alert_events (
  id uuid primary key default gen_random_uuid(),
  rule_id uuid not null references public.alert_rules(id) on delete cascade,
  mint_address text references public.tokens(mint_address) on delete set null,
  title text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  triggered_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.ingestion_runs (
  id bigint generated by default as identity primary key,
  provider text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  tokens_discovered integer not null default 0,
  snapshots_saved integer not null default 0,
  error_message text
);

create index if not exists token_snapshots_mint_time_idx on public.token_snapshots (mint_address, captured_at desc);
create index if not exists alert_rules_owner_scope_idx on public.alert_rules (owner_scope, enabled);
create index if not exists alert_events_rule_time_idx on public.alert_events (rule_id, triggered_at desc);

alter table public.tokens enable row level security;
alter table public.token_snapshots enable row level security;
alter table public.token_risk_checks enable row level security;
alter table public.alert_rules enable row level security;
alter table public.alert_events enable row level security;
alter table public.ingestion_runs enable row level security;

-- V2 accesses these tables only from private server routes using a server secret.
-- Add end-user policies and Supabase Auth before making MemeRadar multi-user or public.
